- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify: restart chrony

- name: Enable timesyncd
  systemd:
    name: chronyd
    enabled: yes
    state: started
